kind: pipeline
type: exec
name: Build Cachix

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: Update flake
  commands:
  - nix --experimental-features "nix-command flakes" -Lv flake update
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable
- name: Run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" -Lv flake check
- name: Build local
  commands:
  - nix build ".#nixosConfigurations.local.config.system.build.toplevel" --json | \
    nix run nixpkgs#jq -- ".[].outputs.out" --raw-output | \
    nix run nixpkgs#cachix -- push diffumist


trigger:
  branch:
  - main
  event:
  - push
  cron:
  - daily



