# ssh hostname 'ssh-keygen -y -f /etc/ssh/ssh_host_ed25519_key' | nix run nixpkgs#ssh-to-age
keys:
  - &diffumist age1mgw2q0ytdsnyxh40me6fu5pvcvcf7nug3dm05s8wu0v9ay20eenqatudqj
  - &bitsflow age1nrgzhh3tz7sd4xat7xhacp9mgy03s6f8kgksj4ylx89apl0twupsc3tes3
  - &liteserver age14euf85fkar532dkxc4p3mstz92nfjlwl4vdgvf5wfm89v4tpgeeqgw5780
  - &dedirock age1kyfqu2ccdj68lspn85735ph76chsnlaff2pdmfmx3ru5dx8dfanqm8pjxe
  - &hostdzire age1rkshe6y7r5gz2tpsxtrvnc7a8j5v3puvak04maat7xkssqmggs5qfwkvv5
  - &nosla-lax age1afmdepa6ya8h8cymxn39mjzr6wx5suem75ley8kghjqx0xt3g47q66t2nj
  - &nosla-sjc age1scl30w074ghz9qlh8lkk8zwnwu9jxezllt04hs7ynudkt7dta4aq9sapp7
  - &phoenix age192s80znrftygj6673sp6af7lpjzxtrvh9gztcp2unn2vy7hdyevq4ddd07
  - &solidvps age135tv74d20v9qc772l63tjgczw4tq3pj86rd6qet69vhe5cf5g3hsq8ucs3
  - &colocrossing age1u4r8qrpmh6p8amxsyumn6htpps2lw5ntpfq4rdtzzzk4gqs22gjslpafyz
  - &vmrack age1pawz4g2qw2awk5mpdgwzzc95p23x0wm04awufrsfy2pvy4zv0g5sc2f3n4
  - &geelinx-jp age1dxeeh73zgq0r329wc6rssxs3tzm47mykfl6htah6czfc9aullaesvy883h
  - &geelinx-mys age1j0gjqjx6lnca8ftg67xjpqgwunk6cd3nt4jkrqtpl5p6n7a9yegqklzj2x
  - &geelinx-us age19hzt079n4sa6gdel6ll4xzq2mfmwf4z7r0rsksf6489nqjrta4fqjm6687
  - &noboard age1vctyp0l4v0wtgjc6n0n3lw2nzffddhzpvtmhklq5wgh3v4d43vdsjl7szc
  - &wawo age1laq2l7pnax405ua70grkefguk4m4zalfjkvj0ky7dzsu2h5sdc6s034jtt
  - &texas age1kewlmdu3tf4hckf0mxnjnyxakm0r03vlqqza5te89var4rjx24vqnk44zz
creation_rules:
  - path_regex: ^nixos/hawkpoint/.*\.(json|ya?ml|keytab)$
    key_groups:
      - age:
          - *diffumist
  - path_regex: ^nixos/liteserver/.*\.(json|ya?ml|keytab)$
    key_groups:
      - age:
          - *liteserver
          - *diffumist
  - path_regex: ^nixos/dedirock/.*\.(json|ya?ml|keytab)$
    key_groups:
      - age:
          - *dedirock
          - *diffumist
  - path_regex: ^nixos/hostdzire/.*\.(json|ya?ml|keytab)$
    key_groups:
      - age:
          - *hostdzire
          - *diffumist
  - path_regex: ^nixos/phoenix/.*\.(json|ya?ml|keytab)$
    key_groups:
      - age:
          - *phoenix
          - *diffumist
  - path_regex: ^nixos/solidvps/.*\.(json|ya?ml|keytab)$
    key_groups:
      - age:
          - *solidvps
          - *diffumist
  - path_regex: ^nixos/colocrossing/.*\.(json|ya?ml|keytab)$
    key_groups:
      - age:
          - *colocrossing
          - *diffumist
  - path_regex: ^nixos/bitsflow/.*\.(json|ya?ml|keytab)$
    key_groups:
      - age:
          - *bitsflow
          - *diffumist
  - path_regex: ^nixos/nosla-lax/.*\.(json|ya?ml|keytab)$
    key_groups:
      - age:
          - *nosla-lax
          - *diffumist
  - path_regex: ^nixos/nosla-sjc/.*\.(json|ya?ml|keytab)$
    key_groups:
      - age:
          - *nosla-sjc
          - *diffumist
  - path_regex: ^nixos/vmrack/.*\.(json|ya?ml|keytab)$
    key_groups:
      - age:
          - *vmrack
          - *diffumist
  - path_regex: ^nixos/geelinx-jp/.*\.(json|ya?ml|keytab)$
    key_groups:
      - age:
          - *geelinx-jp
          - *diffumist
  - path_regex: ^nixos/geelinx-mys/.*\.(json|ya?ml|keytab)$
    key_groups:
      - age:
          - *geelinx-mys
          - *diffumist
  - path_regex: ^nixos/geelinx-us/.*\.(json|ya?ml|keytab)$
    key_groups:
      - age:
          - *geelinx-us
          - *diffumist
  - path_regex: ^nixos/noboard/.*\.(json|ya?ml|keytab)$
    key_groups:
      - age:
          - *noboard
          - *diffumist
  - path_regex: ^nixos/wawo/.*\.(json|ya?ml|keytab)$
    key_groups:
      - age:
          - *wawo
          - *diffumist
  - path_regex: ^nixos/texas/.*\.(json|ya?ml|keytab)$
    key_groups:
      - age:
          - *texas
          - *diffumist
