# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  clash = {
    pname = "clash";
    version = "2021.07.03";
    src = fetchurl {
      sha256 = "1d6mq8qbkiz1f6fy91l2cdq32rk38kp479rf2ky73304a2rq2v9g";
      url = "https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-amd64-2021.07.03.gz";
    };
    
  };
  smartdns-china-list = {
    pname = "smartdns-china-list";
    version = "055ce4ded5164990dc41707e3e282f915e85c466";
    src = fetchgit {
      url = "https://github.com/felixonmars/dnsmasq-china-list";
      rev = "055ce4ded5164990dc41707e3e282f915e85c466";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "07k6yscx7kn4pp7l51slqk018k8pz825k1b1znaxg9j05xsilv5k";
    };
    
  };
}
