# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  smartdns-china-list = {
    pname = "smartdns-china-list";
    version = "91f5991f38b10d0a34da189c50667d9b6b1f659e";
    src = fetchgit {
      url = "https://github.com/felixonmars/dnsmasq-china-list";
      rev = "91f5991f38b10d0a34da189c50667d9b6b1f659e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0rm0pnzicvk7z0wv0639svzg3a79561qabszyhdp5s5clnmswr8g";
    };
    
  };
}
