# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  materia-kde = {
    pname = "materia-kde";
    version = "0209857d0afa3c678d1b915ebc0d8fb708a4c013";
    src = fetchgit {
      url = "https://github.com/diffumist/materia-kde";
      rev = "0209857d0afa3c678d1b915ebc0d8fb708a4c013";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0x8pm1n8c4ick2vvfqp3y4zzmzn2gi0hax7cs3fjg2c2zpbh0hji";
    };
    
  };
  smartdns-china-list = {
    pname = "smartdns-china-list";
    version = "8f35a52a2602f811531965f658df6bdc422d5e94";
    src = fetchgit {
      url = "https://github.com/felixonmars/dnsmasq-china-list";
      rev = "8f35a52a2602f811531965f658df6bdc422d5e94";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1wxm30j99iy7nci00cv4aisbzcpf6kkdjf47dn7aj5ymaqd922x2";
    };
    
  };
}
