[apple-emoji-font]
src.github = "samuelngs/apple-emoji-ttf"
fetch.url = "https://github.com/samuelngs/apple-emoji-ttf/releases/download/$ver/ttf-apple-emoji.pkg.tar.zst"

[xsz]
src.github_tag = "SaltyKitkat/xsz"
src.include_regex = "^v[0-9]+\\.[0-9]+\\.[0-9]+$"
fetch.github = "SaltyKitkat/xsz"
cargo_lock = [ "Cargo.lock" ]
