[maxmind-geoip]
src.git = "https://github.com/Dreamacro/maxmind-geoip"
src.branch = "release"
fetch.github = "Dreamacro/maxmind-geoip"
git.branch = "release"
[material-nvim]
src.git = "https://github.com/marko-cerovac/material.nvim"
fetch.github = "marko-cerovac/material.nvim"
[rime-pinyin-moegirl]
src.manual = "20210923"
fetch.url = "https://github.com/outloudvi/mw2fcitx/releases/download/20211014/moegirl.dict.yaml"
