# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  apple-emoji-font = {
    pname = "apple-emoji-font";
    version = "macos-26-20260219-2aa12422";
    src = fetchurl {
      url = "https://github.com/samuelngs/apple-emoji-ttf/releases/download/macos-26-20260219-2aa12422/ttf-apple-emoji.pkg.tar.zst";
      sha256 = "sha256-bKP82lRDdnXo6lXNwa0G1MM7SFsE6t0OdHY/BAv5wCE=";
    };
  };
  cli-proxy-api = {
    pname = "cli-proxy-api";
    version = "6.9.39";
    src = fetchurl {
      url = "https://github.com/router-for-me/CLIProxyAPI/releases/download/v6.9.39/CLIProxyAPI_6.9.39_linux_amd64.tar.gz";
      sha256 = "sha256-ympWaEfdRsPr7fplXOFjTSya3pZN2BZKGAgJz2oanOk=";
    };
  };
}
