# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  material-nvim = {
    pname = "material-nvim";
    version = "596270a53ac5e19a3b9f9f1777d7e99dcf67f71e";
    src = fetchgit {
      url = "https://github.com/marko-cerovac/material.nvim";
      rev = "596270a53ac5e19a3b9f9f1777d7e99dcf67f71e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0zzdks5dgfz19srflvxa4jj9gxzbany6a697p000vaq5zb59k9v2";
    };
  };
  maxmind-geoip = {
    pname = "maxmind-geoip";
    version = "5ad5a0c87646df616a2574dbf69b316e688fdbf0";
    src = fetchgit {
      url = "https://github.com/Dreamacro/maxmind-geoip";
      rev = "5ad5a0c87646df616a2574dbf69b316e688fdbf0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0a8n1gb3ddgnqrcgizfz7gjniplrdwhnixy238lybxf6lpi5dpn0";
    };
  };
  rime-pinyin-moegirl = {
    pname = "rime-pinyin-moegirl";
    version = "20220114";
    src = fetchurl {
      url = "https://github.com/outloudvi/mw2fcitx/releases/download/20220114/moegirl.dict.yaml";
      sha256 = "0n8c4bvzklgm02rai2kli2iql7qbwh06n7qs863ny75aam4aq1r4";
    };
  };
  rime-pinyin-zhwiki = {
    pname = "rime-pinyin-zhwiki";
    version = "20220101";
    src = fetchurl {
      url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.3/zhwiki-20220101.dict.yaml";
      sha256 = "0z17bx7jky7nybv20ymnsa88qilg92qm09m4sqqbfd83vjj27kmw";
    };
  };
  ydcv-rs = {
    pname = "ydcv-rs";
    version = "7756945e0e44c138416727f66f9e7a81b896792c";
    src = fetchgit {
      url = "https://github.com/farseerfc/ydcv-rs";
      rev = "7756945e0e44c138416727f66f9e7a81b896792c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1zvh19nzi60w5ka0c34s72aqk0iajlsczgyssvmxfz6xcr3s1lza";
    };
    cargoLock = {
      lockFile = ./ydcv-rs-7756945e0e44c138416727f66f9e7a81b896792c/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
}
