name: "build"
on:
  push:
  schedule:
    - cron: '0 8 * * *'
jobs:
  cachix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable-small
      - uses: cachix/cachix-action@v10
        with:
          name: diffumist
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Flake Update
        run: |
          git config --local user.email "flakes-actions[bot]@users.noreply.github.com"
          git config --local user.name "flakes-actions[bot]"
          nix flake update --commit-lock-file
      - name: Flake Checks
        run: nix flake check -Lv
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: flakes-actions
          force: true
