name: "Cachix cache"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  cachix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes ca-references
            access-tokens = github.com=${{ secrets.ACESS_TOKEN }}
      - uses: cachix/cachix-action@v10
        with:
          name: diffumist
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Configure git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
      - name: Flake update
        run: |
          nix flake update
          git add -A
          git commit -m "Automatic update flakes"
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Flake checks
        run: nix flake check -Lv
      - name: Push changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: flakes-actions
          force: true