name: "build and push"
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v14
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/vij683ly7sl95nnhb67bdjjfabclr85m/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Flake update
      run: nix flake update
    - name: Flake check
      run: nix flake check --print-build-logs
    - name: Cachix push
      run: |
          nix build ".#nixosConfigurations.local.config.system.build.toplevel" --json | \
          nix run nixpkgs#jq -- ".[].outputs.out" --raw-output | \
          nix run nixpkgs#cachix -- push diffumist
      env:

        CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
