name: "Cachix-build"
on:
  push:
  schedule:
    - cron: '0 8 * * *'
jobs:
  cachix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v14
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/vij683ly7sl95nnhb67bdjjfabclr85m/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
    - run: nix flake update
    - run: git add -A
    - uses: cachix/cachix-action@v10
      with:
        name: cachix
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - name: Nix build
      run: nix build ".#nixosConfigurations.local.config.system.build.toplevel"

