name: "Cachix"
on:
  push:
  schedule:
    - cron: '0 8 * * 0'
jobs:
  cachix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v14
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/vij683ly7sl95nnhb67bdjjfabclr85m/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Flake update
      run: nix flake update
    - uses: cachix/cachix-action@v10
      with:
        name: cachix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
